import sympy

def card_generated_subgroup(x, p):
    """Cardinal of the multiplicative subgroup generated by x mod p."""
    return len(set(pow(x, i, p) for i in range(p)))

def order(x, p):
    """Multiplicative order of x mod p."""
    xi = 1
    for i in range(1, p):
        xi = (xi * x) % p  # xi = x^i mod p
        if xi == 1:
            return i

p = 11
for x in range(1, p):
    assert order(x, p) == card_generated_subgroup(x, p)
    # print(x, order(x, p))

def smallest_mulgen_mod(p):
    """Smallest generator of F_p*."""
    for g in range(1, p):
        if order(g, p) == p - 1:
            return g

def smallest_mulgen_mod_alt(p):
    """Smallest generator of F_p*, alternative method."""
    strict_divs = sympy.divisors(p - 1)[:-1]
    for g in range(1, p):
        if all(pow(g, d, p) != 1 for d in strict_divs):
            return g

def smallest_mulgen_mod_alt2(p):
    """Smallest generator of F_p*, alternative method, improved"""
    test_exps = [(p - 1) // q for q in sympy.primefactors(p - 1)]
    for g in range(1, p):
        if all(pow(g, d, p) != 1 for d in test_exps):
            return g

for p in (2, 3, 5, 7, 11, 13, 17, 19, 29, 541, 7919, 28151, 104729):
    assert smallest_mulgen_mod(p) == \
            smallest_mulgen_mod_alt(p) == \
            smallest_mulgen_mod_alt2(p)

print(smallest_mulgen_mod(28151))
