

# This file was *autogenerated* from the file rsa_factoring.sage
from sage.all_cmdline import *   # import sage library

_sage_const_510143758735509025530880200653196460532653147 = Integer(510143758735509025530880200653196460532653147); _sage_const_1 = Integer(1)
n = _sage_const_510143758735509025530880200653196460532653147 

f = n.factor(algorithm="qsieve")
print(f)
t = timeit('n.factor(algorithm="qsieve")', number=_sage_const_1 , repeat=_sage_const_1 )
print(t)

f = n.factor()
print(f)
t = timeit('n.factor()', number=_sage_const_1 , repeat=_sage_const_1 )
print(t)

